-- 1.a Database and Schema Setup
CREATE OR REPLACE DATABASE YOUTUBE_TRENDING_ANALYTICS;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA MART;

USE DATABASE YOUTUBE_TRENDING_ANALYTICS;
USE SCHEMA RAW;

-- 1.b Create Stages
CREATE OR REPLACE STAGE RAW.STAGE_TRENDING;
CREATE OR REPLACE STAGE RAW.STAGE_CATEGORY;

-- 1.c Create Raw Trending Table (+ country)
CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE TABLE RAW.RAW_YOUTUBE_TRENDING AS
SELECT
    $1::VARCHAR AS video_id,
    $2::VARCHAR AS title,
    $3::TIMESTAMP_NTZ AS published_at,
    $4::VARCHAR AS channel_id,
    $5::VARCHAR AS channel_title,
    $6::NUMBER AS category_id,
    $7::TIMESTAMP_NTZ AS trending_date,
    $8::NUMBER AS view_count,
    $9::NUMBER AS likes,
    $10::NUMBER AS dislikes,
    $11::NUMBER AS comment_count,
    SUBSTR(METADATA$FILENAME, 1, 2) AS country
FROM @RAW.STAGE_TRENDING
    (FILE_FORMAT => RAW.CSV_FORMAT);

-- 1.d Validate raw Trending Table
SELECT country, COUNT (*) FROM RAW.RAW_YOUTUBE_TRENDING
GROUP BY country
ORDER BY country;

SELECT * FROM RAW.RAW_YOUTUBE_TRENDING LIMIT 10;
    
-- 1.e Create raw Category Table (+ country)
CREATE OR REPLACE FILE FORMAT RAW.JSON_FORMAT
    TYPE = JSON;

CREATE OR REPLACE TABLE RAW.RAW_YOUTUBE_CATEGORY AS
SELECT
    SUBSTR(METADATA$FILENAME, 1, 2) AS country,
    $1 AS raw_category
FROM @RAW.STAGE_CATEGORY
    (FILE_FORMAT => RAW.JSON_FORMAT);

-- 1.f Validate raw Category Table
SELECT country, COUNT (*) FROM RAW.RAW_YOUTUBE_CATEGORY
GROUP BY country
ORDER BY country;

SELECT * FROM RAW.RAW_YOUTUBE_CATEGORY LIMIT 10;